Maritza/Controllers/ProyectController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Maritza.Controllers.Base;
using MaritzaBusness;
using MaritzaData;
using MaritzaData.ConfigClasses;
using MaritzaData.Filters;

namespace Maritza.Controllers
{
    [Authorize(Roles = RolesApp.Rol_Administrador)]
    public class ProyectController : BaseController
    {
        //Objets seccion
        ProyectB ProyectB = new ProyectB();



        // GET: Proyect
        public ActionResult Index(fltProyects filters = null)
        {
            ViewBag.Filter = filters;
            var lstProyects = ProyectB.GetAll(filters);
            if(Request.IsAjaxRequest())
                return PartialView("_Index",lstProyects);
            return View(lstProyects);
        }

        // GET: Proyect/Details/5
        public ActionResult Details(int id)
        {
            var proyect = ProyectB.getById(id);
            if (proyect == null)
            {
                return HttpNotFound();
            }
            return View(proyect);
        }

        // GET: Proyect/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proyect/Create
        [HttpPost]
        public ActionResult Create(tblProyects model)
        {
            if (model == null)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error con el controlador";
                return View(model);
            }
            Response response = new Response();

            model.Active = true;
            model.UpdatedDate = model.CreatedDate = DateTime.Now;
            model.UpdatedBy = model.CreatedBy = 1;



            string Route = SaveImage(model.ImageBase);
            if (Route.Length > 0 && Route != "")
            {
                model.Image = Route;
            }
            response = ProyectB.Create(model);

            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";
            return RedirectToAction("Index");
        }

        // GET: Proyect/Edit/5
        public ActionResult Edit(int id)
        {

            var proyect = ProyectB.getById(id);

            return View(proyect);
        }

        // POST: Proyect/Edit/5
        [HttpPost]
        public ActionResult Edit(tblProyects model)
        {
            if (model == null)
            {
                return HttpNotFound();
            }
            string Route = SaveImage(model.ImageBase);
            if (Route.Length > 0 && Route != "")
            {
                model.Image = Route;
            }
            model.UpdatedDate = DateTime.Now;
            model.UpdatedBy = 2;

            Response response = ProyectB.Update(model);

            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";

            return RedirectToAction("Index");
        }



        // POST: Proyect/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var model = ProyectB.getById(id);
            if (model == null)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                RedirectToAction("Index");
            }
            model.Active = false;
            model.DeletedDate = DateTime.Now;
            model.DeletedBy = 3;
            Response response = ProyectB.Delete(model);

            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";
            return RedirectToAction("Index");
        }
    }
}

Maritza/Controllers/ProyectsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Maritza.Controllers.Base;
using MaritzaBusness;
using MaritzaData;
using MaritzaData.ConfigClasses;
using MaritzaData.Filters;

namespace Maritza.Controllers
{
    [Authorize(Roles = RolesApp.Rol_Administrador)]
    public class ProyectsController : BaseController
    {
        ProyectCharacteristicsB ProyectCharacteristicsB = new ProyectCharacteristicsB();
        CharacteristicsB CharacteristicsB = new CharacteristicsB();
        ProyectDetailsB ProyectDetailsB = new ProyectDetailsB();
        ProyectImagesB ProyectImagesB = new ProyectImagesB();
        ProyectTypesB ProyectTypesB = new ProyectTypesB();
        PublishesB PublishB = new PublishesB();
        ProyectB ProyectB = new ProyectB();
        GenderB GenderB = new GenderB();
        TopicsB TopicsB = new TopicsB();
        public ActionResult Index(fltProyects filters = null)
        {
            ViewBag.Filter = filters;
            var lstProyects = ProyectB.GetAll(filters);
            if (Request.IsAjaxRequest())
                return PartialView("_Index", lstProyects);
            return View(lstProyects);
        }

        public ActionResult Details(int id)
        {
            var model = ProyectB.getById(id);
            if (model == null)
                return HttpNotFound();


            var MainPagePublish = PublishB.GetMainPageByProyectID(model.ProyectID);
            var ProyectPublish = PublishB.GetProyectByProyectID(model.ProyectID);
            model.MainPagePublish = MainPagePublish;
            model.ProyectPublish = ProyectPublish;

            var lstModelProyectCharacteristics = ProyectCharacteristicsB.GetListByProyectID(model.ProyectID);
            model.lstModelProyectCharacteristics = lstModelProyectCharacteristics;

            var lstModelProyectImages = ProyectImagesB.GetListByProyectID(model.ProyectID);
            model.lstModelProyectImages = lstModelProyectImages;

            var MainImage = ProyectImagesB.GetMainImageByProyectID(model.ProyectID);
            model.MainImage = MainImage;

            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.lstProyectTypes = ProyectTypesB.GetList();
            ViewBag.lstTopics = TopicsB.GetList();
            ViewBag.lstGenders = GenderB.GetList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(tblProyects model)
        {
            ViewBag.lstProyectTypes = ProyectTypesB.GetList();
            ViewBag.lstTopics = TopicsB.GetList();
            ViewBag.lstGenders = GenderB.GetList();
            if (model == null)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error con el controlador";
                return View(model);
            }

            model.Active = true;
            model.UpdatedDate = model.CreatedDate = DateTime.Now;
            model.UpdatedBy = model.CreatedBy = CurrentUserID;
            Response response = ProyectB.Create(model);
            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }

            tblProyectDetails tblProyectDetails = new tblProyectDetails();
            tblProyectDetails.ProyectID = model.ProyectID;
            tblProyectDetails.Active = true;
            tblProyectDetails.CreatedBy = tblProyectDetails.UpdatedBy = CurrentUserID;
            tblProyectDetails.CreatedDate = tblProyectDetails.UpdatedDate = DateTime.Now;
            Response response_ = ProyectDetailsB.Create(tblProyectDetails);
            if (response_.Result != Result.Ok)
            {
                //something wrong 
            }
            if (model.lstCharacteristics != null)
            {
                if (model.lstCharacteristics.Count > 0)
                {
                    foreach (var characteristic in model.lstCharacteristics)
                    {
                        try
                        {
                            var exists = CharacteristicsB.CheckIfExistsCharacteristicByID(int.Parse(characteristic));
                            if (exists)
                            {
                                tblProyectCharacteristics tblProyectCharacteristics = new tblProyectCharacteristics();
                                tblProyectCharacteristics.ProyectID = model.ProyectID;
                                tblProyectCharacteristics.CharacteristicID = int.Parse(characteristic);
                                tblProyectCharacteristics.Active = true;
                                tblProyectCharacteristics.CreatedBy = CurrentUserID;
                                tblProyectCharacteristics.CreatedDate = DateTime.Now;
                                Response reponse = ProyectCharacteristicsB.Create(tblProyectCharacteristics);
                                if (reponse.Result != Result.Ok)
                                {
                                    //log error
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            //log error
                        }
                    }
                }
            }
            if (!string.IsNullOrEmpty(model.MainImageBase))
            {
                string url = SaveImage(model.MainImageBase, model.ProyectID);
                if (!string.IsNullOrEmpty(url))
                {
                    tblProyectImages tblProyectImages = new tblProyectImages();
                    tblProyectImages.Url = url;
                    tblProyectImages.IsMainImage = true;
                    tblProyectImages.ProyectID = model.ProyectID;
                    tblProyectImages.Active = true;
                    tblProyectImages.CreatedBy = CurrentUserID;
                    tblProyectImages.CreatedDate = DateTime.Now;
                    ProyectImagesB.Create(tblProyectImages);
                }
            }
            if (model.ImageBase != null)
            {
                if (model.ImageBase.Count > 0)
                {

                    foreach (var strImage in model.ImageBase)
                    {
                        string urlImage = SaveImage(strImage, model.ProyectID);
                        if (!string.IsNullOrEmpty(urlImage))
                        {
                            tblProyectImages tblProyectImages = new tblProyectImages();
                            tblProyectImages.Url = urlImage;
                            tblProyectImages.IsMainImage = false;
                            tblProyectImages.ProyectID = model.ProyectID;
                            tblProyectImages.Active = true;
                            tblProyectImages.CreatedBy = CurrentUserID;
                            tblProyectImages.CreatedDate = DateTime.Now;
                            ProyectImagesB.Create(tblProyectImages);
                        }
                    }

                }
            }
            if (!string.IsNullOrEmpty(model.StartDateMainPage) && !string.IsNullOrEmpty(model.EndDateMainPage))
            {
                tblPublishes tblPublish = new tblPublishes();
                tblPublish.ProyectID = model.ProyectID;
                tblPublish.PublishTypeID = 1;//Main page
                tblPublish.PriorityLevel = model.PrirityMainPage;//Baja 3 - Mediana 2 - Alta 3
                tblPublish.StarDate = DateTime.ParseExact(model.StartDateMainPage, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                tblPublish.EndDate = DateTime.ParseExact(model.EndDateMainPage, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                tblPublish.Active = true;
                tblPublish.CreatedBy = tblPublish.UpdatedBy = CurrentUserID;
                tblPublish.CreatedDate = tblPublish.UpdatedDate = DateTime.Now;

                Response response__ = PublishB.Create(tblPublish);
                if (response__.Result != Result.Ok)
                {
                    //error log
                }
            }
            if (!string.IsNullOrEmpty(model.StartDateProyects) && !string.IsNullOrEmpty(model.EndDateProyects))
            {
                tblPublishes tblPublish = new tblPublishes();
                tblPublish.ProyectID = model.ProyectID;
                tblPublish.PublishTypeID = 2;//Proyects
                tblPublish.PriorityLevel = model.PrirityProyects;//Baja 3 - Mediana 2 - Alta 3
                tblPublish.StarDate = DateTime.ParseExact(model.StartDateProyects, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                tblPublish.EndDate = DateTime.ParseExact(model.EndDateProyects, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                tblPublish.Active = true;
                tblPublish.CreatedBy = tblPublish.UpdatedBy = CurrentUserID;
                tblPublish.CreatedDate = tblPublish.UpdatedDate = DateTime.Now;

                Response response___ = PublishB.Create(tblPublish);
                if (response___.Result != Result.Ok)
                {
                    //error log
                }
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var model = ProyectB.getById(id);
            if (model == null)
                return HttpNotFound();

            ViewBag.lstProyectTypes = ProyectTypesB.GetList();
            ViewBag.lstTopics = TopicsB.GetList();
            ViewBag.lstGenders = GenderB.GetList();

            var MainPagePublish = PublishB.GetMainPageByProyectID(model.ProyectID);
            var ProyectPublish = PublishB.GetProyectByProyectID(model.ProyectID);

Maritza/Views/Proyects/Details.cshtml
@model tblProyects
@{
    ViewBag.Title = "Detalles de proyecto";
}
<div class="container mt-5 mb-3 pt-5 ">
    <div class="card">

        <div class="card-header">
            <h3>
                @ViewBag.Title
            </h3>
        </div>
        <div class="card-body m-3 ">

            <div class="row ">
                <div class="col-4 ">
                    @Html.LabelFor(modelItem => modelItem.ProyectID, new { @class = "fw-bold" }):
                    @Html.DisplayFor(modelItem => modelItem.ProyectID)
                </div>
                <div class="col-4">
                    @Html.LabelFor(modelItem => modelItem.Title, new { @class = "fw-bold" }):
                    @Html.DisplayFor(modelItem => modelItem.Title)
                </div>
                <div class="col-12 mt-3">
                    @Html.LabelFor(modelItem => modelItem.Description, new { @class = "fw-bold" }):
                    @Html.DisplayFor(modelItem => modelItem.Description)
                </div>
                <div class="col-4 mt-3">
                    @Html.LabelFor(modelItem => modelItem.TopicID, new { @class = "fw-bold" }):
                    @Html.DisplayFor(modelItem => modelItem.TopicName)
                </div>
                <div class="col-4 mt-3">
                    @Html.LabelFor(modelItem => modelItem.ProyectTypeID, new { @class = "fw-bold" }):
                    @Html.DisplayFor(modelItem => modelItem.ProyectTypeName)
                </div>
                <div class="col-4 mt-3">
                    @Html.LabelFor(modelItem => modelItem.GenderID, new { @class = "fw-bold" }):
                    @Html.DisplayFor(modelItem => modelItem.GenderName)
                </div>
                <div class="col-4 mt-3">
                    @Html.LabelFor(modelItem => modelItem.Budget, new { @class = "fw-bold" }):
                    @if (Model.Budget != null)
                    {
                        Model.Budget.Value.ToString("F2");
                        //<TEXT> @value </TEXT>
                    }
                    else
                    {
                        <TEXT> Sin estimación </TEXT>
                    }
                    @Html.DisplayFor(modelItem => modelItem.Budget)
                </div>
            </div>


            @if (Model.lstModelProyectCharacteristics != null)
            {
                if (Model.lstModelProyectCharacteristics.Count > 0)
                {
                    <div class="row">
                        <div class="col-12 mt-3">
                            @Html.Label("Caracteristicas", new { @class = "fw-bold" })
                        </div>
                        <div class="col-12 mt-3">
                            <div class="row">

                                @foreach (var Characteristics in Model.lstModelProyectCharacteristics)
                                {

                                    <div class="col-3">
                                        @Characteristics.CharacteristicName
                                    </div>
                                }


                            </div>
                        </div>
                    </div>
                }
            }


            <div class="row mt-3">

                @if (@Model.MainPagePublish != null)
                {
                    <div class="col-4 show-date-main-page">
                        <label class="form-label fw-bold ">Publicar por fechas en [Pagina principal]</label>
                        <span class="validation-mainpage-dates text-danger "></span>
                    </div>
                }

                @if (@Model.ProyectPublish != null)
                {
                    <div class="col-4 show-date-proyects">
                        <label class="form-label fw-bold ">Publicar por fechas en [Proyectos]</label>
                        <span class="validation-proyects-dates text-danger "></span>
                    </div>
                }
            </div>
            <div class="row">
                @if (@Model.MainPagePublish != null)
                {
                    <div class="col-4 show-date-main-page">
                        <label class="form-label fw-bold">Fecha inicio</label>
                        <input id="StartDateMainPage" name="StartDateMainPage" type="text" class="form-control" value="@Model.MainPagePublish.StarDate.ToString("dd/MM/yyyy")" disabled />
                    </div>
                }
                @if (@Model.ProyectPublish != null)
                {
                    <div class="col-4 show-date-proyects">
                        <label class="form-label fw-bold ">Fecha inicio</label>
                        <input id="StartDateProyects" name="StartDateMainPage" type="text" class="form-control" value="@Model.ProyectPublish.StarDate.ToString("dd/MM/yyyy")" disabled />
                    </div>
                }
            </div>
            <div class="row">
                @if (@Model.MainPagePublish != null)
                {
                    <div class="col-4 show-date-main-page">
                        <label class="form-label fw-bold">Fecha final</label>
                        <input id="EndDateMainPage" name="StartDateMainPage" type="text" class="form-control" value="@Model.MainPagePublish.StarDate.ToString("dd/MM/yyyy")" disabled />

                    </div>
                }
                @if (@Model.ProyectPublish != null)
                {
                    <div class="col-4 show-date-proyects">
                        <label class="form-label fw-bold ">Fecha final</label>
                        <input id="EndDateProyects" name="StartDateMainPage" type="text" class="form-control" value="@Model.ProyectPublish.StarDate.ToString("dd/MM/yyyy")" disabled />

                    </div>
                }
            </div>
            <div class="row">
                <div class="col-4 show-date-main-page">
                    @if (@Model.MainPagePublish != null)
                    {
                        <label class="form-label fw-bold">Prioridad en pagina principal</label>
                        <select name="PrirityMainPage" class="form-control" disabled>
                            <option value="1">Alta</option>
                            <option value="2">Mediana</option>
                            <option value="3" selected>Baja</option>
                        </select>
                    }
                </div>
                <div class="col-4 show-date-proyects">
                    @if (@Model.ProyectPublish != null)
                    {
                        <label class="form-label fw-bold ">Prioridad en proyectos</label>
                        <select name="PrirityProyects" class="form-control" disabled>
                            <option value="1">Alta</option>
                            <option value="2">Mediana</option>
                            <option value="3" selected>Baja</option>
                        </select>
                    }
                </div>
            </div>


            <div class="row">
                <!--Imgs-->
                <div class="col-12">
                    @Html.Label("Imagenes", new { @class = "fw-bold" })
                </div>

                <div class="col-12 mt-3">
                    <div class="row">
                        <div class="col-12 bg-dark rounded-bottom-3 py-2" role="button" data-bs-toggle="collapse" data-bs-target="#CollapseImage-1" aria-expanded="false" aria-controls="#CollapseImage-1">
                            <label class="form-label fw-bold text-white" style="cursor:pointer;">Imagen 1 (Principal)</label>
                        </div>
                        <div id="CollapseImage-1" class="col-12 m-0 w-100 collapse bg-lightborder rounded-bottom-3 text-center">
                            @if (Model.MainImage != null)
                            {
                                if (!string.IsNullOrEmpty(Model.MainImage.Url))
                                { 
                                    <img class="rounded-3 mt-2 object-fit" src="@Url.Content(Model.MainImage.Url)" style="max-width: 50%;"/>
                                }
                                else
                                {
                                    <img class="rounded-3 mt-2" src="@Url.Content("~\\Content\\Img\\Personal\\Klaus-Hargreeves.The-Umbrella-Academy_.jpg")" />
                                }
                            }
                            else
                            {
                                <img class="rounded-3 mt-2" src="@Url.Content("~\\Content\\Img\\Personal\\Klaus-Hargreeves.The-Umbrella-Academy_.jpg")" />

                            }

                        </div>
                    </div>
                </div>

                @if (Model.lstModelProyectImages != null)
                {
                    if (Model.lstModelProyectImages.Count > 0)
                    {
                        int index = 2;
                        foreach (var images in Model.lstModelProyectImages)
                        {
                            <div class="col-12 mt-3">
                                <div class="row">
                                    <div class="col-12 bg-dark rounded-bottom-3 py-2" role="button" data-bs-toggle="collapse" data-bs-target="#CollapseImage-@index" aria-expanded="false" aria-controls="#CollapseImage-@index">
                                        <label class="form-label fw-bold text-white" style="cursor:pointer;">Imagen @index</label>
                                    </div>
                                    <div id="CollapseImage-@index" class="col-12 m-0 w-100 collapse bg-lightborder rounded-bottom-3 text-center">
                                        <img class="rounded-3 mt-2" src="@Url.Content(images.Url)" title="Image-@index" />
                                    </div>
                                </div>
                            </div>
                            index++;
                        }
                    }
                }

            </div>
        </div>
        <div class="card-footer">
            <div class="row p-2">
                <div class="col-2">
                    <a class="btn btn-secondary w-100" href="@Url.Action("Index","Proyects",null)">Regresar</a>
                </div>
                <div class="col-2  offset-6">
                    <button id="btnDelete" class="btn btn-danger w-100">Eliminar</button>
                </div>
                <div class="col-2">
                    <a class="btn btn-primary w-100" href="@Url.Action("Edit", "Proyects", new {@id=Model.ProyectID})">Editar</a>
                </div>
            </div>

        </div>
    </div>

</div>
@section scripts{

    <script>
        $(function () {
            $("#btnDelete").click(function () {
                Swal.fire({
                    title: "¿Deseas eliminar el proyecto?",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Si, eliminar.",
                    cancelButtonText: "No, mantener."
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = '@Url.Action("Delete", "Proyects")' + "?id=" + '@Model.ProyectID';
                    }
                });
            });


        });

    </script>

}

Maritza/Views/Proyects/Index.cshtml
@model PagedList.StaticPagedList<dtoProyects>
@{
    ViewBag.Title = "Proyectos";
    var filters = ViewBag.Filter as MaritzaData.Filters.fltProyects;

}


<div class="container mt-5 pt-5">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-10">
                    <h1 class="h3 p-2">@ViewBag.Title </h1>
                </div>
                <div class="col-2 align-self-center">
                    <a class="btn btn-secondary w-100" href="@Url.Action("Create","Proyects",null)">Agregar</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            @using (Ajax.BeginForm(
            new AjaxOptions
            {
                HttpMethod = "get",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "ModelList",
            }
            ))
            {


                <div class="row p-3">
                    <div class="col-3">
                        @Html.LabelFor(f => filters.ProyectID, new { @class = "form-label" })
                        @Html.TextBoxFor(f => filters.ProyectID, new { @class = "form-control", @placeholder = "ID", @Value = "" })
                    </div>
                    <div class="col-3">
                        @Html.LabelFor(f => filters.Title, new { @class = "form-label" })
                        @Html.TextBoxFor(f => filters.Title, new { @class = "form-control", @placeholder = "Proyecto" })
                    </div>
                    <div class="col-3">
                        @Html.LabelFor(f => filters.Description, new { @class = "form-label" })
                        @Html.TextBoxFor(f => filters.Description, new { @class = "form-control", @placeholder = "Descripción" })
                    </div>
                    <div class="offset-1 col-2 ">
                        <a id="Clean" class="btn btn-sm btn-primary w-100 mb-1" href="@Url.Action("Index","Proyects",null)">Limpiar</a>
                        <input id="btnSearch" class="btn btn-sm btn-success w-100" type="submit" value="Buscar" />
                    </div>
                </div>
                @Html.Partial("_index", Model);
                @Html.HiddenFor(model => filters.ProyectID_Sort)
                @Html.HiddenFor(model => filters.Title_Sort)
                @Html.HiddenFor(model => filters.Description_Sort)
                @Html.HiddenFor(model => filters.Active_Sort)
                @Html.HiddenFor(model => filters.SortingOrder)
            }
        </div>
    </div>

</div>