Maritza/Controllers/TopicsController.cs
using MaritzaBusness;
using MaritzaData.ConfigClasses;
using MaritzaData.Filters;
using MaritzaData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Maritza.Controllers.Base;

namespace Maritza.Controllers
{
    public class TopicsController : BaseController
    {
        TopicsB TopicsB = new TopicsB();

        public ActionResult Index(fltTopics filters = null)
        {
            ViewBag.Filter = filters;
            var lstTopicss = TopicsB.GetAll(filters);
            if (Request.IsAjaxRequest())
                return PartialView("_Index", lstTopicss);
            return View(lstTopicss);
        }

        public ActionResult Details(int id)
        {
            var Topics = TopicsB.getById(id);
            if (Topics == null)
            {
                return HttpNotFound();
            }
            return View(Topics);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(tblTopics model)
        {
            if (model == null)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error con el controlador";
                return View(model);
            }
            

            model.Active = true;
            model.UpdatedDate = model.CreatedDate = DateTime.Now;
            model.UpdatedBy = model.CreatedBy = CurrentUserID;

            Response response = TopicsB.Create(model);

            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {

            var Topics = TopicsB.getById(id);

            return View(Topics);
        }
        [HttpPost]
        public ActionResult Edit(tblTopics model)
        {
            if (model == null)
            {
                return HttpNotFound();
            }
           
            model.UpdatedDate = DateTime.Now;
            model.UpdatedBy = CurrentUserID;

            Response response = TopicsB.Update(model);

            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var model = TopicsB.getById(id);
            if (model == null)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                RedirectToAction("Index");
            }
            model.Active = false;
            model.DeletedDate = DateTime.Now;
            model.DeletedBy = CurrentUserID;
            Response response = TopicsB.Delete(model);

            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";
            return RedirectToAction("Index");
        }


        //UploadExcel method
    }
}

Maritza/Views/Topics/Create.cshtml
@model tblTopics
@{
    ViewBag.Title = "Crear temáticas";
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "frm", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary();
    <div class="container pt-5 mt-5 mb-5">

        <div class="card mt-5">
            <div class="card-header">
                <h3>@ViewBag.Title</h3>
            </div>
            <div class="card-body mt-5 ">

                <div class="row ">
                    <div class="col-4 p-1">
                        @Html.LabelFor(model => model.Name, new { @class = "form-label fw-bold" })
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Tematica" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>
            <div class="card-footer">
                <div class="row pt-2">
                    <div class="col-2">
                        <a class="btn btn-secondary w-100" href="@Url.Action("Index")">Regresar</a>
                    </div>
                    <div class="col-2 offset-8">
                        <input class="btn btn-success w-100" type="submit" value="Guardar" />
                    </div>
                </div>

            </div>
        </div>

    </div>

}

@section scripts{
    <link href="@Url.Content("~/Content/cropper.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/Cropper/cropper.js")"></script>
    <script type="text/javascript">
       
    </script>

}

Maritza/Views/Topics/Details.cshtml
@model tblTopics
@{
    ViewBag.Title = "Detalles de temática";
}
<div class="container p-5 mt-5 mb-5">
    <div class="card m-5">
        <div class="card-header">
            <h3> @ViewBag.Title</h3>
        </div>
        <div class="card-body">

            <div class="row ">
                <div class="col-4 ">
                    @Html.LabelFor(modelItem => modelItem.TopicID, new { @class = "fw-bold" }):
                    @Html.DisplayFor(modelItem => modelItem.TopicID)
                </div>
                <div class="col-4">
                    @Html.LabelFor(modelItem => modelItem.Name, new { @class = "fw-bold" }):
                    @Html.DisplayFor(modelItem => modelItem.Name)
                </div>


            </div>
        </div>
        <div class="card-footer">
            <div class="row p-2">
                <div class="col-2">
                    <a class="btn btn-secondary w-100" href="@Url.Action("Index","Topics",null)">Regresar</a>
                </div>

                <div class="col-2  offset-6">
                    <button id="btnDelete" class="btn btn-danger w-100">Eliminar</button>
                </div>
                <div class="col-2">
                    <a class="btn btn-primary w-100" href="@Url.Action("Edit", "Topics", new {@id=Model.TopicID})">Editar</a>
                </div>
            </div>

        </div>
    </div>

</div>

@section scripts{

    <script>
        $(function () {
            $("#btnDelete").click(function () {
                Swal.fire({
                    title: "¿Deseas eliminar la tematica?",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Si, eliminar.",
                    cancelButtonText: "No, mantener."
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = '@Url.Action("Delete", "Topics")' + "?id=" + '@Model.TopicID';
                    }
                });
            });


        });

    </script>

}

Maritza/Views/Topics/Edit.cshtml
@model tblTopics
@{
    ViewBag.Title = "Editar temática";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Topics", FormMethod.Post, new { @id = "frm", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary();
 
    <div class="container p-5 mt-5 mb-5">
        <div class="card mt-5">
            <div class="card-header">
                <h3>@ViewBag.Title</h3>
            </div>
            <div class="card-body">

                <div class="row">
                    <div class="col-4">
                        @Html.LabelFor(model => model.Name, new { @class = "form-label fw-bold" })
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="row mt-3">
                    <div class="col-2">
                        <a class="btn btn-secondary w-100" href="@Url.Action("Index","Topics", new {@id=Model.TopicID})">Regresar</a>
                    </div>
                    <div class="col-2 offset-6">
                        <input id="btnDelete" class="btn btn-danger w-100" type="button" value="Eliminar" />
                    </div>
                    <div class="col-2">
                        <input class="btn btn-success w-100" type="submit" value="Guardar edición" />
                    </div>
                </div>
            </div>
        </div>
    </div>


    @Html.HiddenFor(model => model.TopicID);
    @Html.HiddenFor(model => model.Active);
    @Html.HiddenFor(model => model.CreatedBy);
    @Html.HiddenFor(model => model.CreatedDate);
    @Html.HiddenFor(model => model.UpdatedBy);
    @Html.HiddenFor(model => model.UpdatedDate);
    @Html.HiddenFor(model => model.DeletedBy);
    @Html.HiddenFor(model => model.DeletedDate);
}


@section scripts{
    <script type="text/javascript">



    </script>
}

Maritza/Views/Topics/Index.cshtml
@model PagedList.StaticPagedList<dtoTopics>
@{
    ViewBag.Title = "Temáticas";
    var filters = ViewBag.Filter as MaritzaData.Filters.fltTopics;

}

<div class="container  mt-5 pt-5">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-10">
                    <h1 class="h3 p-2">@ViewBag.Title </h1>
                </div>
                <div class="col-2 align-self-center">
                    <a class="btn btn-secondary w-100" href="@Url.Action("Create","Topics",null)">Agregar</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            @using (Ajax.BeginForm(
            new AjaxOptions
            {
                HttpMethod = "get",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "ModelList",
            }
            ))
            {
             
                <div class="row p-3">
                    <div class="col-3">
                        @Html.LabelFor(f => filters.TopicID, new { @class = "form-label" })
                        @Html.TextBoxFor(f => filters.TopicID, new { @class = "form-control", @placeholder = "ID", @Value = filters.TopicID == 0 ? "" : filters.TopicID.ToString() })
                    </div>
                    <div class="col-3">
                        @Html.LabelFor(f => filters.Name, new { @class = "form-label" })
                        @Html.TextBoxFor(f => filters.Name, new { @class = "form-control", @placeholder = "Temática" })
                    </div>
                    <div class="offset-4 col-2 ">
                        <a id="Clean" class="btn btn-sm btn-primary w-100 mb-1" href="@Url.Action("Index","Topics",null)">Limpiar</a>
                        <input id="btnSearch" class="btn btn-sm btn-success w-100" type="submit" value="Buscar" />
                    </div>
                </div>
                @Html.Partial("_index", Model);
                @Html.HiddenFor(model => filters.TopicID_Sort)
                @Html.HiddenFor(model => filters.Name_Sort)
                @Html.HiddenFor(model => filters.Active_Sort)
                @Html.HiddenFor(model => filters.SortingOrder)
            }
        </div>
    </div>

</div>

Maritza/Views/Topics/_Index.cshtml
@model PagedList.StaticPagedList<dtoTopics>
@using PagedList.Mvc;
@{
    var filters = ViewBag.Filter as MaritzaData.Filters.fltTopics;
}



<div id="ModelList">
    <div class="table-responsive">
        <table class="table table-striped ">
            <thead>
                <tr>
                    <th>
                        @Html.ActionLink("ID", "Index", new { SortingOrder = filters.TopicID_Sort, ProyectID = filters.TopicID, Name = filters.Name }, htmlAttributes: new { })
                    </th>
                    <th>
                        @Html.ActionLink("Nombre", "Index", new { SortingOrder = filters.Name_Sort, ProyectID = filters.TopicID, Name = filters.Name }, htmlAttributes: new { })
                    </th>
                </tr>
            </thead>
            <tbody>

                @if (Model.Count == 0)
                {
                    <tr>
                        <td colspan="5">
                            Sin registros
                        </td>
                    </tr>
                }
                else
                {
                    foreach (var element in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(elementItem => element.TopicID)</td>
                            <td>@Html.DisplayFor(elementItem => element.Name)</td>
                            <td>
                                <a href="@Url.Action("Details", new {@id=element.TopicID})" class="text-decoration-none">Detalles</a>
                                |
                                <a href="@Url.Action("Edit", new {@id=element.TopicID})" class="text-decoration-none">Editar</a>

                            </td>
                        </tr>
                    }
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5">
                        <div id="ModelList" class="" data-otf-target="#ModelList">
                            @{
                                var vPagedlistRenderOptions = PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.ClassicPlusFirstAndLast,
                                               new AjaxOptions()
                                               {
                                                   HttpMethod = "GET",
                                                   UpdateTargetId = "ModelList",
                                                   OnBegin = "ShowLoading()",
                                                   OnComplete = "HideLoading()"
                                               });
                                vPagedlistRenderOptions.LiElementClasses = new[] { "page-item" };
                                vPagedlistRenderOptions.UlElementClasses = new[] { "pagination" };
                            }
                            @Html.PagedListPager(Model, page => Url.Action("Index",
                           new
                           {
                               PageNumber = page,
                               ProyectTypeID = filters.TopicID,
                               Title = filters.Name,
                               SortingOrder = filters.SortingOrder
                           }), vPagedlistRenderOptions)
                        </div>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>