Maritza/Controllers/ProyectController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Maritza.Controllers.Base;
using MaritzaBusness;
using MaritzaData;
using MaritzaData.ConfigClasses;
using MaritzaData.Filters;

namespace Maritza.Controllers
{
    [Authorize(Roles = RolesApp.Rol_Administrador)]
    public class ProyectController : BaseController
    {
        //Objets seccion
        ProyectB ProyectB = new ProyectB();



        // GET: Proyect
        public ActionResult Index(fltProyects filters = null)
        {
            ViewBag.Filter = filters;
            var lstProyects = ProyectB.GetAll(filters);
            if(Request.IsAjaxRequest())
                return PartialView("_Index",lstProyects);
            return View(lstProyects);
        }

        // GET: Proyect/Details/5
        public ActionResult Details(int id)
        {
            var proyect = ProyectB.getById(id);
            if (proyect == null)
            {
                return HttpNotFound();
            }
            return View(proyect);
        }

        // GET: Proyect/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proyect/Create
        [HttpPost]
        public ActionResult Create(tblProyects model)
        {
            if (model == null)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error con el controlador";
                return View(model);
            }
            Response response = new Response();

            model.Active = true;
            model.UpdatedDate = model.CreatedDate = DateTime.Now;
            model.UpdatedBy = model.CreatedBy = 1;



            string Route = SaveImage(model.ImageBase);
            if (Route.Length > 0 && Route != "")
            {
                model.Image = Route;
            }
            response = ProyectB.Create(model);

            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";
            return RedirectToAction("Index");
        }

        // GET: Proyect/Edit/5
        public ActionResult Edit(int id)
        {

            var proyect = ProyectB.getById(id);

            return View(proyect);
        }

        // POST: Proyect/Edit/5
        [HttpPost]
        public ActionResult Edit(tblProyects model)
        {
            if (model == null)
            {
                return HttpNotFound();
            }
            string Route = SaveImage(model.ImageBase);
            if (Route.Length > 0 && Route != "")
            {
                model.Image = Route;
            }
            model.UpdatedDate = DateTime.Now;
            model.UpdatedBy = 2;

            Response response = ProyectB.Update(model);

            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";

            return RedirectToAction("Index");
        }



        // POST: Proyect/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var model = ProyectB.getById(id);
            if (model == null)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                RedirectToAction("Index");
            }
            model.Active = false;
            model.DeletedDate = DateTime.Now;
            model.DeletedBy = 3;
            Response response = ProyectB.Delete(model);

            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";
            return RedirectToAction("Index");
        }
    }
}

Maritza/Controllers/ProyectsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Maritza.Controllers.Base;
using MaritzaBusness;
using MaritzaData;
using MaritzaData.ConfigClasses;
using MaritzaData.Filters;

namespace Maritza.Controllers
{
    [Authorize(Roles = RolesApp.Rol_Administrador)]
    public class ProyectsController : BaseController
    {
        ProyectCharacteristicsB ProyectCharacteristicsB = new ProyectCharacteristicsB();
        CharacteristicsB CharacteristicsB = new CharacteristicsB();
        ProyectDetailsB ProyectDetailsB = new ProyectDetailsB();
        ProyectImagesB ProyectImagesB = new ProyectImagesB();
        ProyectTypesB ProyectTypesB = new ProyectTypesB();
        PublishesB PublishB = new PublishesB();
        ProyectB ProyectB = new ProyectB();
        GenderB GenderB = new GenderB();
        TopicsB TopicsB = new TopicsB();
        public ActionResult Index(fltProyects filters = null)
        {
            ViewBag.Filter = filters;
            var lstProyects = ProyectB.GetAll(filters);
            if (Request.IsAjaxRequest())
                return PartialView("_Index", lstProyects);
            return View(lstProyects);
        }

        public ActionResult Details(int id)
        {
            var model = ProyectB.getById(id);
            if (model == null)
                return HttpNotFound();


            var MainPagePublish = PublishB.GetMainPageByProyectID(model.ProyectID);
            var ProyectPublish = PublishB.GetProyectByProyectID(model.ProyectID);
            model.MainPagePublish = MainPagePublish;
            model.ProyectPublish = ProyectPublish;

            var lstModelProyectCharacteristics = ProyectCharacteristicsB.GetListByProyectID(model.ProyectID);
            model.lstModelProyectCharacteristics = lstModelProyectCharacteristics;

            var lstModelProyectImages = ProyectImagesB.GetListByProyectID(model.ProyectID);
            model.lstModelProyectImages = lstModelProyectImages;

            var MainImage = ProyectImagesB.GetMainImageByProyectID(model.ProyectID);
            model.MainImage = MainImage;

            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.lstProyectTypes = ProyectTypesB.GetList();
            ViewBag.lstTopics = TopicsB.GetList();
            ViewBag.lstGenders = GenderB.GetList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(tblProyects model)
        {
            ViewBag.lstProyectTypes = ProyectTypesB.GetList();
            ViewBag.lstTopics = TopicsB.GetList();
            ViewBag.lstGenders = GenderB.GetList();
            if (model == null)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error con el controlador";
                return View(model);
            }

            model.Active = true;
            model.UpdatedDate = model.CreatedDate = DateTime.Now;
            model.UpdatedBy = model.CreatedBy = CurrentUserID;
            Response response = ProyectB.Create(model);
            if (response.Result != Result.Ok)
            {
                ViewBag.ErrorMessage = $"Ocurrio un error al guardar la información";
                return View(model);
            }

            tblProyectDetails tblProyectDetails = new tblProyectDetails();
            tblProyectDetails.ProyectID = model.ProyectID;
            tblProyectDetails.Active = true;
            tblProyectDetails.CreatedBy = tblProyectDetails.UpdatedBy = CurrentUserID;
            tblProyectDetails.CreatedDate = tblProyectDetails.UpdatedDate = DateTime.Now;
            Response response_ = ProyectDetailsB.Create(tblProyectDetails);
            if (response_.Result != Result.Ok)
            {
                //something wrong 
            }
            if (model.lstCharacteristics != null)
            {
                if (model.lstCharacteristics.Count > 0)
                {
                    foreach (var characteristic in model.lstCharacteristics)
                    {
                        try
                        {
                            var exists = CharacteristicsB.CheckIfExistsCharacteristicByID(int.Parse(characteristic));
                            if (exists)
                            {
                                tblProyectCharacteristics tblProyectCharacteristics = new tblProyectCharacteristics();
                                tblProyectCharacteristics.ProyectID = model.ProyectID;
                                tblProyectCharacteristics.CharacteristicID = int.Parse(characteristic);
                                tblProyectCharacteristics.Active = true;
                                tblProyectCharacteristics.CreatedBy = CurrentUserID;
                                tblProyectCharacteristics.CreatedDate = DateTime.Now;
                                Response reponse = ProyectCharacteristicsB.Create(tblProyectCharacteristics);
                                if (reponse.Result != Result.Ok)
                                {
                                    //log error
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            //log error
                        }
                    }
                }
            }
            if (!string.IsNullOrEmpty(model.MainImageBase))
            {
                string url = SaveImage(model.MainImageBase, model.ProyectID);
                if (!string.IsNullOrEmpty(url))
                {
                    tblProyectImages tblProyectImages = new tblProyectImages();
                    tblProyectImages.Url = url;
                    tblProyectImages.IsMainImage = true;
                    tblProyectImages.ProyectID = model.ProyectID;
                    tblProyectImages.Active = true;
                    tblProyectImages.CreatedBy = CurrentUserID;
                    tblProyectImages.CreatedDate = DateTime.Now;
                    ProyectImagesB.Create(tblProyectImages);
                }
            }
            if (model.ImageBase != null)
            {
                if (model.ImageBase.Count > 0)
                {

                    foreach (var strImage in model.ImageBase)
                    {
                        string urlImage = SaveImage(strImage, model.ProyectID);
                        if (!string.IsNullOrEmpty(urlImage))
                        {
                            tblProyectImages tblProyectImages = new tblProyectImages();
                            tblProyectImages.Url = urlImage;
                            tblProyectImages.IsMainImage = false;
                            tblProyectImages.ProyectID = model.ProyectID;
                            tblProyectImages.Active = true;
                            tblProyectImages.CreatedBy = CurrentUserID;
                            tblProyectImages.CreatedDate = DateTime.Now;
                            ProyectImagesB.Create(tblProyectImages);
                        }
                    }

                }
            }
            if (!string.IsNullOrEmpty(model.StartDateMainPage) && !string.IsNullOrEmpty(model.EndDateMainPage))
            {
                tblPublishes tblPublish = new tblPublishes();
                tblPublish.ProyectID = model.ProyectID;
                tblPublish.PublishTypeID = 1;//Main page
                tblPublish.PriorityLevel = model.PrirityMainPage;//Baja 3 - Mediana 2 - Alta 3
                tblPublish.StarDate = DateTime.ParseExact(model.StartDateMainPage, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                tblPublish.EndDate = DateTime.ParseExact(model.EndDateMainPage, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                tblPublish.Active = true;
                tblPublish.CreatedBy = tblPublish.UpdatedBy = CurrentUserID;
                tblPublish.CreatedDate = tblPublish.UpdatedDate = DateTime.Now;

                Response response__ = PublishB.Create(tblPublish);
                if (response__.Result != Result.Ok)
                {
                    //error log
                }
            }
            if (!string.IsNullOrEmpty(model.StartDateProyects) && !string.IsNullOrEmpty(model.EndDateProyects))
            {
                tblPublishes tblPublish = new tblPublishes();
                tblPublish.ProyectID = model.ProyectID;
                tblPublish.PublishTypeID = 2;//Proyects
                tblPublish.PriorityLevel = model.PrirityProyects;//Baja 3 - Mediana 2 - Alta 3
                tblPublish.StarDate = DateTime.ParseExact(model.StartDateProyects, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                tblPublish.EndDate = DateTime.ParseExact(model.EndDateProyects, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                tblPublish.Active = true;
                tblPublish.CreatedBy = tblPublish.UpdatedBy = CurrentUserID;
                tblPublish.CreatedDate = tblPublish.UpdatedDate = DateTime.Now;

                Response response___ = PublishB.Create(tblPublish);
                if (response___.Result != Result.Ok)
                {
                    //error log
                }
            }
            ViewBag.ErrorMessage = $"Se guardo la información exitosamente";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var model = ProyectB.getById(id);
            if (model == null)
                return HttpNotFound();

            ViewBag.lstProyectTypes = ProyectTypesB.GetList();
            ViewBag.lstTopics = TopicsB.GetList();
            ViewBag.lstGenders = GenderB.GetList();

            var MainPagePublish = PublishB.GetMainPageByProyectID(model.ProyectID);
            var ProyectPublish = PublishB.GetProyectByProyectID(model.ProyectID);

Maritza/Views/Proyect/Index.cshtml
@model PagedList.StaticPagedList<dtoProyects>
@{
    ViewBag.Title = "Proyectos";
    var filters = ViewBag.Filter as MaritzaData.Filters.fltProyects;

}




<div class="container pt-4 mb-5 mt-4">
    <div class="card mt-5">
        <div class="card-header">
            <div class="row">
                <div class="col-10">
                    <h1 class="h3 p-2">Proyectos</h1>
                </div>
                <div class="col-2 mt-2">
                    <a class="btn btn-secondary w-100" href="@Url.Action("Create","Proyect",null)">Agregar</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            @using (Ajax.BeginForm(
            new AjaxOptions
            {
                HttpMethod = "get",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "ModelList",
            }
            ))
            {
              
                <div class="row mt-2">
                    <div class="offset-10 col-2 ">
                        <a id="Clean" class="btn btn-sm btn-primary w-100" href="@Url.Action("Index","Proyect",null)">Limpiar</a>
                    </div>
                    <div class="offset-10 col-2 mt-2">
                        <input id="btnSearch" class="btn btn-sm btn-success w-100" type="submit" value="Buscar" />
                    </div>
                </div>
                <hr/>
                <div class="row p-3">
                    <div class="col-3">
                        @Html.Label("ID", new { @class = "form-label" })
                        @Html.TextBoxFor(f => filters.ProyectID, new { @class = "form-control", @placeholder = "ID", @Value = "" })
                    </div>
                    <div class="col-3">
                        @Html.Label("Título", new { @class = "form-label" })
                        @Html.TextBoxFor(f => filters.Title, new { @class = "form-control", @placeholder = "Título" })
                    </div>
                    <div class="col-3">
                        @Html.Label("Descripción", new { @class = "form-label" })
                        @Html.TextBoxFor(f => filters.Description, new { @class = "form-control", @placeholder = "Descripción" })
                    </div>
                    <div class="col-3">
                        @Html.Label("Comentario", new { @class = "form-label" })
                        @Html.TextBoxFor(f => filters.Comment, new { @class = "form-control", @placeholder = "Comentario" })
                    </div>

                </div>

                @Html.Partial("_index", Model);

                @Html.HiddenFor(model => filters.ProyectID_Sort)
                @Html.HiddenFor(model => filters.Title_Sort)
                @Html.HiddenFor(model => filters.Description_Sort)
                @Html.HiddenFor(model => filters.Comment_Sort)
                @Html.HiddenFor(model => filters.Active_Sort)
                @Html.HiddenFor(model => filters.SortingOrder)

            }
        </div>
    </div>

</div>

Maritza/Views/Proyect/_Index.cshtml
@model PagedList.StaticPagedList<dtoProyects>
@using PagedList.Mvc;
@{
    var filters = ViewBag.Filter as MaritzaData.Filters.fltProyects;
}



<div id="ModelList">
    <div class="table-responsive">
        <table class="table table-striped ">
            <thead>
                <tr>
                    <th>
                        @Html.ActionLink("ID", "Index", new { SortingOrder = filters.ProyectID_Sort, ProyectID = filters.ProyectID, Title = filters.Title, Description = filters.Description, Comment = filters.Comment }, htmlAttributes: new { })
                    </th>
                    <th>
                        @Html.ActionLink("Título", "Index", new { SortingOrder = filters.Title_Sort, ProyectID = filters.ProyectID, Title = filters.Title, Description = filters.Description, Comment = filters.Comment }, htmlAttributes: new { })
                    </th>
                    <th>
                        @Html.ActionLink("Descripción", "Index", new { SortingOrder = filters.Description_Sort, ProyectID = filters.ProyectID, Title = filters.Title, Description = filters.Description, Comment = filters.Comment }, htmlAttributes: new { })
                    </th>
                    <th>
                        @Html.ActionLink("Comentario", "Index", new { SortingOrder = filters.Comment_Sort, ProyectID = filters.ProyectID, Title = filters.Title, Description = filters.Description, Comment = filters.Comment }, htmlAttributes: new { })
                    </th>
                </tr>
            </thead>
            <tbody>

                @if (Model.Count == 0)
                {
                    <tr>
                        <td colspan="5">
                            Sin registros
                        </td>
                    </tr>
                }
                else
                {
                    foreach (var element in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(elementItem => element.ProyectID)</td>
                            <td>@Html.DisplayFor(elementItem => element.Title)</td>
                            <td>@Html.DisplayFor(elementItem => element.Description)</td>
                            <td>@Html.DisplayFor(elementItem => element.Comment)</td>
                            <td>
                                <a href="@Url.Action("Details", new {@id=element.ProyectID})" class="text-decoration-none">Detalles</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5">
                        <div id="ModelList" class="" data-otf-target="#ModelList">
                            @{
                                var vPagedlistRenderOptions = PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.ClassicPlusFirstAndLast,
                                               new AjaxOptions()
                                               {
                                                   HttpMethod = "GET",
                                                   UpdateTargetId = "ModelList",
                                                   OnBegin = "ShowLoading()",
                                                   OnComplete = "HideLoading()"
                                               });
                                vPagedlistRenderOptions.LiElementClasses = new[] { "page-item" };
                                vPagedlistRenderOptions.UlElementClasses = new[] { "pagination" };
                            }
                            @Html.PagedListPager(Model, page => Url.Action("Index",
                           new
                           {
                               PageNumber = page,
                               ProyectID = filters.ProyectID,
                               Title = filters.Title,
                               Description = filters.Description,
                               Comment = filters.Comment,
                               ProyectID_Sort = filters.ProyectID_Sort,
                               Title_Sort = filters.Title_Sort,
                               Description_Sort = filters.Description_Sort,
                               Comment_Sort = filters.Comment_Sort,
                               SortingOrder = filters.SortingOrder

                           }), vPagedlistRenderOptions)
                        </div>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>